dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

after_success:
  - bash <(curl -s https://codecov.io/bash)
